### ISSUE TITLE
EitherAsync missing functions?

### ISSUE THREAD

**Issue by jjm340** [gigobyte/purify#122]
When I use an EitherAsync where is mapLeft?

**Comment by gigobyte** [comment]
EitherAsync only has `map` and `chain` basically, it doesn't support the whole Either API, but I'm glad  I'm receiving useful feedback. I'll add additional methods to EitherAsync and MaybeAsync so that working with them is easier.

**Comment by JBuijgers** [comment]
Would be great to have this feature. Is there a clean way to work around this atm? Especially mapLeft, since I'm trying to move from EitherAsync<unknown, User> to EitherAsync<Failure, User>.

Great work on the library so far, the documentation provides a really good DX, this has become my number one FP library in TS. Keep up the good work!

**Comment by gigobyte** [comment]
If you want to do it in-place then you can do
```js
EitherAsync(async ({ liftEither }) => {
    const value = await liftEither(someEither.mapLeft(...mapping...))
})
```
otherwise you will have to use `chain`, which is not ergonomic, I agree.

**Comment by JBuijgers** [comment]
Ah, I see now what went wrong, I had EitherAsync<Failure, Organization> as the return type of the function. I should have added these generics to the EitherAsync call, else type argument inference will not work. Below code works perfectly.
```ts
byId = (id: number) =>
  EitherAsync<Failure, Organization>(async ({ throwE, liftEither }) => {
    return await liftEither(
      (await this.api.byId(id).run()).mapLeft(
        fail(throwE)('get-org', `No organization with id ${id}`)
      )
    )
  })
```

Tnx for the help :+1:

**Comment by gigobyte** [comment]
Yeah, this is very awkward, I'm currently working on improving the Maybe and EitherAsync API. They are both experimental and I wasn't sure if people would like them since I haven't seen any solution like this anywhere in JS/TS. I'm glad I'm seeing some issues, this means people have started using them and are already encountering the limitations of the API. :tada:

By the way, don't spend too much time optimizing your current solution, soon it will be just:
```js
byId = (id: number) =>
   this.api.byId(id).mapLeft(fail(throwE)('get-org', `No organization with id ${id}`))
```
I just have to get around to polish the API, docs and release a new version.

**Comment by JBuijgers** [comment]
Tnx so much! Great to have this, going switch to the master branch for this in the meanwhile :smile:

**Comment by JBuijgers** [comment]
Would it be possible to create a next npm tag for the master branch? I'm having some trouble with getting my project to compile using the git repo master branch (e.g. using purify-ts/src as import, webpack telling me it can't find it, etc), and would like to use all new cutting edge features of this library.

**Comment by gigobyte** [comment]
@JBuijgers Done.

**Comment by JBuijgers** [comment]
Tnx! Just started using it, one small problem though, the main field in package.json points to lib/index.js, but compiled files are placed in the root directory (e.g. node_modules/purify-ts/index.js). Besides that, the next tag works perfectly after moving the files to the lib directory :+1:

**Comment by JBuijgers** [comment]
@gigobyte Would be great if this could be fixed, I'm up for some CI/CD trouble ahead of me, trying to prevent any patch-package actions :smile:

**Comment by gigobyte** [comment]
I'm not available until the end of the week so I won't be able to change anything.

**Comment by JBuijgers** [comment]
Tnx for the fast reply, good to know, patch-package to the rescue for now.
