### ISSUE TITLE
discussion: declaratively unwrap Either<L, Promise<R>> into EitherAsync<L, R>?

### ISSUE THREAD

**Issue by cakekindel** [gigobyte/purify#146]
It'd be really nice if in my beautiful declarative fluent call chain, i could unwrap a `Either<L, Promise<R>>` into a `EitherAsync<L, R>` (or just as well a `Maybe<Promise<T>>` into a `MaybeAsync<T>`)

If I have:
```ts
function saveEgg(egg: Egg): Promise<Egg> { ... }
function breakEgg(egg: Egg): BrokenEgg { ... }

const egg = new Egg();
```
and my requirements are to save (asynchronous) and then break this egg, and I would like to have an `EitherAsync<Error, Egg>` at the end, here's how I picture this happening in an ideal world:
```ts
const savedEgg = Either.of<Error, Egg>(egg)  // Either<Error, Egg>
                       .map(saveEgg)         // Either<Error, Promise<Egg>>
                       .unwrapAsync()        // EitherAsync<Error, Egg>
                       .map(breakEgg);       // EitherAsync<Error, BrokenEgg>
```

right now I can kind of do this with `.either` and a couple helper functions:
```ts
function eitherAsyncFromLeft<L>(value: L): EitherAsync<L, never>;
function eitherAsyncFromPromise<T>(promise: Promise<T>): EitherAsync<Error, T>

const savedEgg = Either.of<Error, Egg>(egg) // Either<Error, Egg>
                       .map(saveEgg)        // Either<Error, Promise<Egg>>
                       .either(
                           eitherAsyncFromLeft,
                           eitherAsyncFromPromise,
                       )                    // EitherAsync<Error, Egg>
                       .map(breakEgg);      // EitherAsync<Error, BrokenEgg>
```

**Comment by gigobyte** [comment]
The problem with JS promises is that they run immediately after they are created, so in your example when you map with `saveEgg`, your Promise will run asynchronously during the execution of your hypothetical `unwrapAsync` function, and by that moment it's too late to hijack the execution.

Here's what I think will result in a better API:
```js
const savedEgg = Either.of<Error, Egg>(egg)  // Either<Error, Egg>
                       .mapAsync(saveEgg)    // EitherAsync<Error, Egg>
                       .map(breakEgg);       // EitherAsync<Error, BrokenEgg>
```

You could have a `chainAsync` as well that acts like a regular `chain` but you pass it a promise. In this example, `mapAsync` will actually return an `EitherAsync` instance, not an `Either`, but since in the future the plan is to mirror the API for both data types (see https://github.com/gigobyte/purify/issues/122) you should not be able to notice the difference.

**Comment by cakekindel** [comment]
I like that API a lot!

And I know promises are not ideal because of their eagerness, I'm in the process of converting my mainly imperative codebase with heavy async await usage so for right now I have to deal with promises.

 do you have any plans to integrate maybe/eitherasync with lazy async structures like [Flutures](https://github.com/fluture-js/Fluture) or [Observables](https://github.com/ReactiveX/rxjs)?

**Comment by gigobyte** [comment]
I haven't used Promise libraries like fluture or bluebird, so I can't say if it would be difficult to integrate, but the plan is to support anything PromiseLike (as in the TS type). Unfortunately anything more than that wouldn't be possible because of the way Either and MaybeAsync are implemented.

**Comment by cakekindel** [comment]
Gotcha, yeah Fluture and Observable are a couple examples of approaching the shortcomings of JS Promises, but you may as well just use an Either of a Fluture or Observable. Thought I would pick your brain on this topic, thank you for sharing your thoughts 😃

**Comment by cakekindel** [comment]
oops

**Comment by kenchan0130** [comment]
Perhaps a function that allows `Either<A, Promise<B>> -> Promise<Either<A, B>>` would be a significant improvement.

**Comment by gigobyte** [comment]
@kenchan0130 When working with Either and Promises, I'm expecting a back-end context. In that case, I prefer using do-notation since it's easier to work with than chaining functions. Here's what I would do:
```
const doTheThing = () => EitherAsync(async ({ liftEither, fromPromise }) => {
  // use liftEither to turn Either<A, B> to B
  const b: B = await liftEither(somethingThatReturnsEither()) 

  // use fromPromise to turn Promise<C> to C
  const c: C = await fromPromise(somethingThatReturnsPromise(b))

  console.log('the result from the promise is: ' + c)
})
```

**Comment by kenchan0130** [comment]
I am aware that there is such the workaround.
But if you expect it to be more useful, it would be nice to have a sequence method like cats of Scala, for example.
http://eed3si9n.com/herding-cats/Traverse.html

**Comment by gigobyte** [comment]
Yes, I'm familiar that you're talking about implementing a non-generic instance of Traversable. I do not consider the solution I provided a workaround, perhaps I've overestimated the need for an imperative API, because that's the only API available right now and I didn't think people would want anything else.

I'm thinking that in the next version EitherAsync should expose:
* the imperative API I showed above, so that people can use the equivalent of do-notation, for- comprehensions etc in TypeScript
* a more declarative API that would look something like:

```ts
const theThing: Promise<Either<A, B>> =
  somethingThatReturnsEither()
    .mapAsync(somethingThatReturnsPromise)
    .ifRight(c => console.log('the result from the promise is: ' + c))
    .run()
```
Here, `mapAsync` would be the `traverse . map` you're looking for, it's just that for a real traverse you need the value inside the data type to be an Applicative (to have an `of` method), which is not really possible / practical in JS/TS.

**Comment by gigobyte** [comment]
The final API is a bit different from what I wrote down here, but it is finished and I'm planning a bigger release soon.
