### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by chenguo** [gigobyte/purify#207]
On NPM it looks like the most recent release is 0.16.0-beta.2. There's been some interface changes in the past month I'd love to have access to, can we get a new release? A beta one will be fine. Thanks!

**Comment by gigobyte** [comment]
I haven't worked on open-source stuff in a while due to personal issues, sorry for that. I'll try to apply the changes from EitherAsync to MaybeAsync soon and push a new beta release. I'd love to make a final 0.16 release, but that includes a lot of work (updating the changelog, making sure everything is polished and ready to be published, writing docs etc) so it won't happen soon.

**Comment by gigobyte** [comment]
`0.16.0-beta.3` is published.

**Comment by chenguo** [comment]
Hope everything will turn out fine for you, thank you for your hard work!
