### ISSUE TITLE
Can Codec handle optional properties?

### ISSUE THREAD

**Issue by ccapndave** [gigobyte/purify#221]
I can't seem to figure out how to write a `Codec` for a structure with optional properties:

```ts
type A = { readonly a?: number };
const aCodec: Codec<A> = Codec.interface({ a: optional(number) });
```

Gives a type error on the assignment of `aCodec`:

```
Type 'Codec<{ a: number | undefined; }>' is not assignable to type 'Codec<A>'.
  Types of property 'encode' are incompatible.
    Type '(input: { a: number | undefined; }) => unknown' is not assignable to type '(input: A) => unknown'.
      Types of parameters 'input' and 'input' are incompatible.
        Type 'A' is not assignable to type '{ a: number | undefined; }
```

**Comment by gigobyte** [comment]
Your example is not working for me either. I can't think of anything that can fix it currently, I've played with making `optional` really optional before and it made the return type of `Codec.interface` a mess.

**Comment by gigobyte** [comment]
Similar issue: https://github.com/neuledge/computed-types/issues/51

**Comment by kulshekhar** [comment]
This seems to be working fine here: https://stackblitz.com/edit/typescript-oqxxlg?file=index.ts

Could this be a typescript version issue?

**Comment by gigobyte** [comment]
@kulshekhar Your example works because TS is not running in "strict" mode.

**Comment by kulshekhar** [comment]
aah .. configured it to strict mode and saw this issue :man_facepalming:

**Comment by gigobyte** [comment]
Since `optional -> undefined` is way easier than `undefined -> optional` I added a special type you can use when you define a Codec.

![image](https://user-images.githubusercontent.com/8791446/98440375-035c5a00-2101-11eb-8fb8-05a6f86f5f4c.png)

**Comment by eduhenke** [comment]
Hi, if you think it would be interesting I've found a way for the properties to be optional in the interface Codec (check my fork at https://github.com/eduhenke/purify/commit/c4ddb81f7729614655b11c7099657c0a7d7d02c6#diff-7163e25aa5ac9a7ad1afcbaf3e8a0f007c669477f87911f36236a8a007782288R127).

However it makes the properties optional for property that are required but undefined, as in the following example:
```typescript
const example = Codec.interface({
  str: string,
  num: number,
  optStr: optional(string),
  none: oneOf([number, undefinedType]),
});

type ExampleType = GetType<typeof example>;
// {
//     str: string;
//     num: number;
// } & {
//     optStr?: string | undefined;
//     none?: number | undefined;
// }
```

If that is not desired, we could maybe add a tag to the Codec, so that it's only true when built with the `optional` Codec, first thing that passes my mind would be: `type Codec<T, Optional extends boolean = false>`, which we could use the second parameter to infer that the property is optional. However I do concur with you that the outputted type as it is not unified, gets a little unreadable.
