### ISSUE TITLE
Strict decoder

### ISSUE THREAD

**Issue by moltar** [gigobyte/purify#223]
I'd like to have a strict decoder that will error out if there is any extra (undefined or undeclared) data.

Is this something that is possible?

Thanks.

**Comment by gigobyte** [comment]
It's fairly straightforward to write a codec combinator that enforces that.
```typescript
const strict = <T extends object>(codec: Codec<T>): Codec<T> =>
  Codec.custom({
    encode: codec.encode,
    decode: (value: unknown) =>
      codec.decode(value).chain((x) => {
        if (Object.keys(x).length !== Object.keys(value as object).length) {
          return Left('')
        }

        return Right(x)
      }),
    schema: () => ({ ...codec.schema(), additionalProperties: false })
  })
```

**Comment by moltar** [comment]
But this doesn't do deep comparison though, right? So you'd need to replace all `Codec.interface` calls with this custom `strict` codec, right?

**Comment by gigobyte** [comment]
`strict` takes a codec as an argument, so you need to wrap the `Codec.interface` instead of replacing it. You can change the implementation so that it does deep comparison of the number of keys. I'm not really interested in adding this function into the library as failing on extra keys is an odd decision.

**Comment by moltar** [comment]
Ok, thank you.
