### ISSUE TITLE
Consider adding the `lib` folder to version control to allow installing from git 

### ISSUE THREAD

**Issue by pyrho** [gigobyte/purify#248]
Adding the `lib` folder to git would allow people to use "pre release" versions.

The drawback is that the committer needs to build before committing (so that the JS an TS files are in sync), this could be done via post/pre hooks are CI (including launching the tests).

I have no experience with Github CI, but I can take a look if this is something that you would be interested in.

**Comment by gigobyte** [comment]
I think the beta releases are good enough, I don't want to be responsible for people using `master` because sometimes I commit stuff that aren't tested or might be removed a couple of hours later. When I publish a beta version at least there's some guarantee that what you're using will be part of the next version.

**Comment by pyrho** [comment]
Fair enough, thanks.
