### ISSUE TITLE
oneOf usage breaks after upgrade to 0.16.0

### ISSUE THREAD

**Issue by moltar** [gigobyte/purify#265]
```ts
export const FOOBAR = Object.freeze(['FOO', 'BAR'] as const)

export const Foobar = oneOf(FOOBAR.map((p) => exactly(p)))
```

Get an error:

```
Argument of type 'Codec<"FOO" | "BAR">[]' is not assignable to parameter of type '[Codec<any>, ...Codec<any>[]]'.
  Property '0' is optional in type 'Codec<"FOO" | "BAR">[]' but required in type '[Codec<any>, ...Codec<any>[]]'. ts(2345)
```

Any ideas on how to solve it?

Thanks.

**Comment by gigobyte** [comment]
It's because `oneOf` was changed to include at least one element (previously `oneof([])` was valid, but it's nonsense).

The problem here is that `Array.map` wipes out the `const` part of that array and the result is `Codec<"FOO" | "BAR">[]`, which is not guaranteed to have at least one element. Unfortunately this is a problem with TS, not purify.

Here are some possible solutions:
* You could use an enum for the definition of FOOBAR and use `enumeration` instead of `oneOf`
* You could inline the definition i.e. `oneOf(['FOO', 'BAR').map(exactly)])`

**Comment by moltar** [comment]
Tbh, I'd rather have `oneOf([])`, which might be nonsense, yet still a valid construct.
