### ISSUE TITLE
Add Reader, ReaderAsync, and ReaderEitherAsync types?

### ISSUE THREAD

**Issue by chris-kahn** [gigobyte/purify#266]
It's great to have the `Either` and `EitherAsync` types, I'd like to suggest taking things one step further and allow users to compose functions that share a common context. Similar to `ReaderTaskEither` in `fp-ts` and the `ReaderT` in Haskell.

**Comment by gigobyte** [comment]
Imo `Reader` is useful only when used in a language with do-notation. I don't see a point to use `ReaderEitherAsync<R, E, A>` instead of just `(env: R) => EitherAsync(E, A)`.  I've experimented with it before and came to that conclusion, but let me know if you have interesting usecases.

**Comment by chris-kahn** [comment]
Isn't that a bit like saying `EitherAsync` is only useful in a language with do-notation, just use `async () => Either<E, A>` and `Either.isRight|isLeft`? How would you chain a sequence of calls to `(env: R) => EitherAsync<E, A>` together without having to pass the environment into every function call?

```
const program = fnThatReturnsReaderEitherAsync(42)
  .chain(result => someFn(result.value, true))
  .chain(someOtherFn)
  .map(result => result.value)

program.run(env)
```

**Comment by gigobyte** [comment]
That's correct - I wouldn't implement `EitherAsync` if there was no async/await in JS, it's practically do-notation for the Promise "monad".

I agree passing the environment around is not optimal, but I'm not convinced that anyone would actually use `ReaderEitherAsync`. People that are willing to use it are probably already using `fp-ts`, the others are probably using simpler approches. Personally, I just pass the environment around, stored in the [`req object in express`](https://github.com/gigobyte/ts-fullstack-starter/blob/main/index.d.ts) so that it's passed to my endpoints automatically.
