### ISSUE TITLE
Trying to use Ramda curring with Purify ap

### ISSUE THREAD

**Issue by scorsi** [gigobyte/purify#269]
Hi,

I try to reproduce : https://mostly-adequate.gitbooks.io/mostly-adequate-guide/content/ch10.html#ships-in-bottles. 
This book don't use Purify so I'm asking if Purify has the same behaviour or not than the home-made library in the book.

I'm facing an issue while `curring` with `Maybe` (or `Either`). Here's a sample:
```js
import { Maybe } from "purify-ts"; //  version 0.16.0
import { curry } from "ramda"; //  version 0.27.1

const add = curry((a: number, b: number) => a + b);

Maybe.of(add)
  .ap(Maybe.of(() => 2)) // should be Maybe.of(2)
  .ap(Maybe.of(() => 3)) // should be Maybe.of(5)
  .map(console.log); // prints 5
```
The weird part is that I need to pass a function to `Maybe.of`. How can I rearrange this code to be able to passe direct value ?

Thanks !

**Comment by gigobyte** [comment]
This is a known problem in purify (and not only). Let's start with the normal signature of `<*>` (`ap` in purify and other libraries):
```
f (a -> b) -> f a -> f b
```
Because `<*>` is a normal function, not a method on an object, it means that you can arrange the arguments so that they fit the type definition (e.g. you can do both `a <*> b` and `b <*> a` depending on which variable is the function inside a Maybe). The style of application in your example is inspired by how you would write the example in languages where `ap` is a function instead of a method:
```
// JS
Maybe.of(add).ap(Maybe.of(2)).ap(Maybe.of(3))

// Haskell
Just add <*> Just 2 <*> Just 3
```

In purify, ap is a method on Maybe, so the arguments must be fixed. I had to make a choice, do I want to have `Maybe.of(add).ap(Maybe.of(2))` or `Maybe.of(ap).ap(Maybe.of(add))`, I can choose only one because there can only be 1 type definition for ap (well, in practice there could be more, overloads exist in TS, but this is another topic).

Luckily for me I didn't have to make that decision because purify is fantasy-land compliant and FL defines `ap` like [this](https://github.com/fantasyland/fantasy-land#apply):
```
f a ~> f (a -> b) -> f b
```
This means that the second argument must be a function wrapped in a Maybe. FL is like that for [documentation reasons](https://github.com/fantasyland/fantasy-land/issues/169#issuecomment-248037233), which motivated me to add a second `ap` to purify, but I never came around to doing it.

If you want to implement your example with purify, you will have to reverse the operations like this:
```
Maybe.of(3).ap(Maybe.of(2).ap(Maybe.of(add)))
```
Hope that helps!

**Comment by pyrho** [comment]
Hi there,

Although less readable (imo) than your version, you could write it like this if you really wanted:

```typescript
Maybe.of(2).ap(Maybe.of(1).ap(Maybe.of(add)))
```

The [fantasyland spec](https://github.com/fantasyland/fantasy-land#fantasy-landap-method) says:

> b [where B is the argument to ap] must be an Apply of a function
    If b does not represent a function, the behaviour of fantasy-land/ap is unspecified.

In the Mostly Adequate Guide (great book!) they define `ap()` as  follows:

```javascript
Container.prototype.ap = function (otherContainer) {
  return otherContainer.map(this.$value);
};
```

But in purify, it is define like so:

```typescript
ap<U>(maybeF: Maybe<(value: T) => U>): Maybe<U> {
    return maybeF.isJust() ? this.map(maybeF.extract()) : nothing
  }
```

(notice how the order is inverted, `.map` is called on `this`, rather than on the argument).

I think this may be an error with the example in the book, as from where I'm standing purify conforms to the spec; specifically that the argument to the `ap()` call should be an `Apply` (read `Maybe` in our case).

That being said, I'm not the most knowledgeable on any of those subjects so yeah... (:

**Comment by scorsi** [comment]
Hello thank you both for your answers ! This was very helpful.

The solution you gave here works when we have two arguments but what with more arguments ?

The only solutions I found is:
```typescript
user
  .toEither(Error("User is empty"))
  .chain((user) =>
    Either.sequence([checkEmail(user), checkName(user), checkPassword(user)])
  )
  .chain(([email, name, password]) => createUser(email, name, password))
  .either(
    console.log.bind(console, "Got error:"),
    console.log.bind(console, "Got result:")
  );
```

I try to found a solution with `lift` like this but you see the duplication :
```typescript
lift(createUser)(
  user.toEither(Error("User is empty")).chain(checkEmail),
  user.toEither(Error("User is empty")).chain(checkName),
  user.toEither(Error("User is empty")).chain(checkPassword)
)
  .join()
  .either(
    console.log.bind(console, "Got error:"),
    console.log.bind(console, "Got result:")
  );
```

____

To shorten: What's the best solution to use `curry`-ed function with Purify when the function has more than 2 arguments ?

**Comment by gigobyte** [comment]
Sorry, I didn't get the question. What's stopping you from applying more arguments?

```typescript
email.ap(name.ap(password.ap(birthDate.ap(gender.map(createUser)))))
```

**Comment by scorsi** [comment]
Oh my bad, it's actually working, the issue comes from somewhere else.

Here's the code which's not working:
```typescript
import { Maybe, Just, Either, Right, Nothing } from "purify-ts";
import { curry, lift } from "ramda";

type User = {
  name: string;
  email: string;
  password: string;
};

const checkEmail = (user: User): Either<Error, string> => {
  return Right(user.email);
};

const checkName = (user: User): Either<Error, string> => {
  return Right(user.name);
};

const checkPassword = (user: User): Either<Error, string> => {
  return Right(user.password);
};

const createUser = curry((email: string, name: string, password: string) => {
  console.info(email, name, password);
  return Right(true);
});

const user: Maybe<User> = true
  ? Just({
      name: "John Doe",
      email: "blurp_blurp",
      password: "secret"
    })
  : Nothing;

user
  .toEither(Error("User is empty"))
  .chain((user) => 
    checkPassword(user).ap(checkName(user).ap(checkEmail(user).ap(Either.of(createUser))))
  )
  .join() // This is causing trouble
  .either(
    console.log.bind(console, "Got error:"),
    console.log.bind(console, "Got result:")
  );
```
I got a compile error :
```
❯ npx ts-node index.ts
⨯ Unable to compile TypeScript:
index.ts:38:1 - error TS2684: The 'this' context of type 'Either<Error, Curry<(...args: readonly any[]) => unknown>>' is not assignable to method's 'this' of type 'Either<Error, Either<Error, unknown>>'.
  Type 'Curry<(...args: readonly any[]) => unknown>' is missing the following properties from type 'Either<Error, unknown>': isLeft, isRight, toJSON, inspect, and 32 more.

 38 user
    ~~~~
 39 .toEither(Error("User is empty"))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 41   checkPassword(user).ap(checkName(user).ap(checkEmail(user).ap(Either.of(createUser))))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 42 )
    ~
```

I had to add `.join()` before the `.either()` to be able to get the actual result of the `createUser` function. But when I did add `.join()` I got a compile error which is obscure to me. ^^

I know I'm getting out of this issue contexte, but do you have any clue for my problem ?

**Comment by pyrho** [comment]
If you change `createUser` to:

```typescript
const createUser = (email: string) => (name: string) => (password: string) => {
    console.info(email, name, password);
    return Right(true);
};
```
It will fix your compilation issue.

Typing ramda is pretty hard, and it will sometime confuse the compiler; in my experience ramda and typescript will often cause issues, often forcing you to hint to the compiler what it is you really meant.

Using this syntax (`() => () => () =>`) is a bit more verbose than using ramda's `curry` but will achieve the same results.

**Comment by scorsi** [comment]
Well I must admit that this is not really the answer I expected but... it works lol 
Thank you !

**Comment by pyrho** [comment]
Short of improving (if it can be done) ramda's typings (which are maintained seperate from the ramda project, I think I know why ;P); I don't think there is anything you can do.

By the way, for cases like the one you describe I've been using a little helper that makes things a bit nicer to look at:

```typescript
// The helper
function eitherMap2<E, A, B, C>(
    fa: Either<E, A>,
    fb: Either<E, B>,
    f: (a: A, b: B) => C,
): Either<E, C> {
    return fb.ap(fa.map(a => b => f(a, b)));
}

const y = (user: User) => eitherMap2(checkPassword(user), checkEmail(user), (password, email) => {
    // do something
});
```

The downside is that you have to create one helper per # of arguments you want to handle (ie. eitherMap3, eitherMap4, etc.).

**Comment by gigobyte** [comment]
You had to add `.join()` because your constructor definition is wrong:
```
const createUser = curry((email: string, name: string, password: string) => {
  console.info(email, name, password);
  return Right(true);
});
```
There is no need to return a `Right` here.

Also, a tip: `.ap(Either.of(createUser))` is the same `.map(createUser)`, there's no need to lift the function into an Either :)

**Comment by scorsi** [comment]
Ok so here's the error ! :) 
And what if I don't really have the control over that function which returns a `Either` ?
