### ISSUE TITLE
Loses execution context when using EitherAsync

### ISSUE THREAD

**Issue by eduhenke** [gigobyte/purify#493]
I'm using this library for our application, and we are now instrumenting our application for APM.

However, when using the EitherAsync class, it seems that the execution context is lost.

I've tried to patch the `.then` method(on the dist folder though), as I've read somewhere that custom *then-ables* may lose this async execution context, like so:

![image](https://user-images.githubusercontent.com/8304447/146824781-f65a0bbf-0f29-4bca-9405-4ac4561acb3d.png)

As soon as I've done that, the traces were correctly collected.

Here's more info on how to fix it: https://gist.github.com/Qard/faad53ba2368db54c95828365751d7bc#fixing-thenables-context-loss-with-asyncresource.

I am willing to perform this fix, if you'd think it to be a valid addition.

**Comment by gigobyte** [comment]
Hello, this looks like a purely Node.js thing, is it possible to make it cross-platform?

I'm not that familiar with stack traces and the execution context, can you explain a bit more about the problem?

**Comment by casey-chow** [comment]
Async hooks are a very Node.js concept, so it doesn't seem to be something that can be made cross-platform without some conditional requiring I would guess.

> I'm not that familiar with stack traces and the execution context, can you explain a bit more about the problem?

I think the post @eduhenke is great for explaining the narrow technical need, but the high-level use case is observability. Most APMs need preserved execution context to trace a request flow through various microtasks and events. So for example, if I were to run:

```
app.post('/update-me', async (req, res) => {
  logger.info('getting user');
  const user = await db.user.get({ id: req.userId });
  logger.info('got user', { user });

  user.name = "Joe";
  user.save().then((user) => {
    logger.info("updated user");
  });
});
```

All `logger` statements and the database calls in that request could be linked to the same HTTP request because the execution context is the same across all of them. This is super useful for trying to figure out what happened in a request when looking at a slow endpoint, and losing execution context means that, say, this code:

```
app.post('/update-me', async (req, res) => {
  logger.info('getting user');
  const user = await db.user.get({ id: req.userId });
  logger.info('got user', { user });

  user.name = "Joe";
  await EitherAsync.fromPromise(() => user.save())
    .ifRight((user) => {
      logger.info("updated user");
    });
});
```

The `updated user` trace would not be linked to the request, which limits our ability to observe the behavior of the endpoint.
