### ISSUE TITLE
Design question: instance methods or type functions?

### ISSUE THREAD

**Issue by RPisRyan** [gigobyte/purify#574]
I am implementing some 2D types, trying to learn from API design approach used by Purify. Do you have any guidance on instance method `point.distanceTo(otherPoint)` vs type function `Point.distance(a, b)`? 
I am trying to determine if the instance methods in Purify (`tuple.toArray`, etc) are an ergonomic decision to make the API more approachable to new folks, or are a more useful pattern overall?
Would I be headed in the wrong direction to implement everything as type functions (`Point.distance(a, b)`, `Point.areEqual(a, b)`) and disregard instance functions? I notice that `List` is implemented in this way.

**Comment by gigobyte** [comment]
I'm definitely no thought leader when it comes to library APIs, I don't think my opinion holds much weight.

If treeshaking is a must for your library then `Point.distance(a, b)` is what you want. Purify uses instance methods because the provided data types are designed for chaining a lot of transformations i.e. `data.map().chain().x().y()` so methods are definitely cleaner. If you don't expect that kind of usage of your types then it comes down to personal preference.
