### ISSUE TITLE
isJust/isNothing narrowing

### ISSUE THREAD

**Issue by SamHH** [gigobyte/purify#67]
Prior to using this library, my primary means of simulating a Maybe ADT was to make something Nullable (`T | null`), and treat null as Nothing. In doing so, the following code was possible:

```typescript
const genNullableNum = () => Math.random() > .5 ? Math.random() : null;
const numberPlease = (a: number) => {};

function example() {
    const nullableNum = genNullableNum();

    if (nullableNum === null) return;

    numberPlease(nullableNum);
}
```

This code uses early termination to narrow the type of `nullableNum` to `number`; if you remove that line, the compiler will correctly complain that you're potentially passing `null` to `numberPlease`.

This doesn't appear to be possible with this library, though it's possible I'm misusing it. If you attempt to run similar code using `maybeNum.isNothing()` in the if statement, the type isn't narrowed. Equally, if you run `if (maybeNum.isJust())` the type isn't narrowed inside the if statement either.

The type _does_ narrow if you run `Maybe.ifJust` or `Maybe.isNothing`, however due to that using a callback that doesn't permit the early termination pattern I prefer.

Cheers!

**Comment by gigobyte** [comment]
Hi! Early returns cannot be supported by this library since the type narrowing TypeScript does with return is specific only to null and undefined. There is something similar you can do, which is to use the `extract` method, it has been specifically designed to be context aware so it knows then you've already checked:
```typescript

function example() {
  const maybeNum: Maybe<number> = Just(5)

  const a = maybeNum.extract() // number | undefined

  if (maybeNum.isJust()) {
      const b = maybeNum.extract() // number
  }
}
```
As a final note I would advise using `extract` and `isJust/isNothing` with caution, since they are almost worse alternatives to `map`, `chain`, `alt` or even `caseOf`. Those methods may seem intimidating at the beginning, but learning to use them has great benefits and leads to code that is easier to maintain and reason about.

**Comment by SamHH** [comment]
Ah, that reminds me a little bit of the observable style. I'll take that approach and see how it goes, many thanks for the detailed reply!
