### ISSUE TITLE
Codec with optional `unkown` has unexpected type `unknown` instead of `unknown | undefined`

### ISSUE THREAD

**Issue by emiel** [gigobyte/purify#712]
First off, thanks for the great lib! ;)

In the following codec definition, I'm expecting `Foo.foo` to be of type `unknown | undefined` just like `Foo.bar` is. Is there something special about `unknown` or is this a bug?

```
import * as pur from "purify-ts";

export const fooCodec = pur.Codec.interface({
  foo: pur.optional(pur.unknown),
  bar: pur.optional(pur.boolean),
});

export type Foo = pur.GetType<typeof fooCodec>;
```

<img width="381" alt="image" src="https://github.com/gigobyte/purify/assets/37766/4b768a58-8307-4205-b01d-a774875b0b14">

```
$ tsc --version
Version 5.5.2
```

**Comment by gigobyte** [comment]
That is a feature of TypeScript, it's the same with `any | undefined`. Because `unknown` includes `undefined` in itself it doesn't make a lot of sense to keep it in the definition.

<img width="387" alt="image" src="https://github.com/gigobyte/purify/assets/8791446/230c277a-41f9-45bb-9da0-4738e0d268c8">

**Comment by emiel** [comment]
Of course, that makes sense. Given `any` and `unknown` are TypeScript's [Top type](https://en.wikipedia.org/wiki/Top_type).

Thanks!
